apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: dotnetaccelerator
    tanzu.app.live.view: "true"
    tanzu.app.live.view.application.flavours: steeltoe
    tanzu.app.live.view.application.name: dotnetaccelerator
    autoscaling.knative.dev/minScale: "1"
    autoscaling.knative.dev/maxScale: "1"
  name: dotnetaccelerator
  namespace: default
spec:
  env:
    - name: ASPNETCORE_ENVIRONMENT
      value: Development
    - name: DbType
      value: SQLite
    - name: ConnectionStrings__Database
      value: DataSource=myshareddb;mode=memory;cache=shared
    - name: ASPNETCORE_URLS
      value: http://0.0.0.0:8080;http://0.0.0.0:8090
    - name: Management__Port # should really be 8090, but buildpack version that ships with TAP doesn't allow overriding ASPNETCORE_URLS to do multiport mapping
      value: "8080"
  source:
    git:
      ref:
        branch: dev
      url: https://github.com/macsux/dotnet-accelerator
